### ISSUE TITLE
Add list of columns that will be dropped in Prophet model

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#13]
<a href="https://github.com/iKintosh"><img src="https://avatars.githubusercontent.com/u/25372584?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iKintosh](https://github.com/iKintosh)**
_Friday Jun 17, 2022 at 12:41 GMT_
_Originally opened as https://github.com/tinkoff-ai/etna/issues/757_

----

### 🚀 Feature Request
We show dropped columns during fitting SARIMAX, but don't show it for the Prophet.

### Proposal

We should add the list of dropped columns during fitting of `ProphetModel` like we do for `SARIMAXModel`:

```
  warnings.warn(
      message=f"Prophet model does not work with exogenous features (features unknown in future).\n "
      f"{column_to_drop} will be dropped"
  )
```

**Comment by d-a-bunin** [comment]
Closed by tinkoff-ai#1312.
