### ISSUE TITLE
Implement in-sample and out-sample predictions in `nn` models without exceptions

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#17]
<a href="https://github.com/Mr-Geekman"><img src="https://avatars.githubusercontent.com/u/36005824?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Mr-Geekman](https://github.com/Mr-Geekman)**
_Friday Jul 15, 2022 at 13:59 GMT_
_Originally opened as https://github.com/tinkoff-ai/etna/issues/805_

----

### 🚀 Feature Request

Currently we can't make with `nn` models
* in-sample predictions 
* out-sample predictions there `ts` isn't going straight after the train and only on `horizon` steps in the future
We are throwing exception because of limitation of implementation. However, it is possible and we can implement it.

### Proposal

Add possibility to make
* in-sample predictions
* out-sample predictions with gap

Probably it will be easier to do after merging #776.

### Test cases

1. Make sure current tests pass.
2. Pay attention to tests in `test_inference`, after making in-sample and out-sample with gap possible without the exception, we should probably move `nn` models to a new test case.

### Additional context

This task waits for #787 to finish.

**Comment by d-a-bunin** [comment]
Was moved into #366.
