### ISSUE TITLE
Update `PatchTSModel` to handle integer timestamp

### ISSUE THREAD

**Issue by d-a-bunin** [etna-team/etna#185]
### 🚀 Feature Request

In #178 it was found that `PatchTSModel` fails on data with integer timestamp. It could be fixed.

### Proposal

Fix tests `tests/test_models/test_inference/test_forecast/TestForecastOutSample` for models:
- `PatchTSModel`

This model fails on additional numeric feature, which breaks dimension expectations. It seems like this model can't work with additional features and this probably should be fixed.

We should fix model to work only on `target` column and ignore any additional features.

To discuss:
- Should timestamp be treated as additional numeric feature? It probably should be decided for all the models (`RNNModel`, `MLPModel`, etc)
- Should this model be able to work with additional numeric features?

### Test cases

- Add tests on working with additional features
- Move fixed tests in `tests/test_models/test_inference/test_forecast/TestForecastOutSample` from fail to success category
- Move fixed tests `tests/test_models/test_inference/test_predict/TestPredictInSampleSuffix` from fail to success category

### Additional context

Blocked by #178.

**Comment by martins0n** [comment]
Let's for now fix it to work with only target column.
And add extra task to backlog for support for extra features

**Comment by martins0n** [comment]
We should not use timestamp in integer format column for any dl models

**Comment by d-a-bunin** [comment]
Will be done in #191.
