### ISSUE TITLE
Add public RoadMap

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#19]
<a href="https://github.com/alex-hse-repository"><img src="https://avatars.githubusercontent.com/u/55380696?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alex-hse-repository](https://github.com/alex-hse-repository)**
_Friday Oct 21, 2022 at 09:28 GMT_
_Originally opened as https://github.com/tinkoff-ai/etna/issues/993_

----

### 🚀 Feature Request

We want to share the info about development process with the external users

### Proposal

1. Create public RoadMap.md for the current quarter, using the plans from Miro. There should be a short summary of the current track in the library.
2. Share the link to the roadmap in tg

**Comment by d-a-bunin** [comment]
It was decided to close this issue, because we are going to try setting priorities with Discussion board.
