### ISSUE TITLE
Improve the Readme

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#20]
<a href="https://github.com/alex-hse-repository"><img src="https://avatars.githubusercontent.com/u/55380696?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alex-hse-repository](https://github.com/alex-hse-repository)**
_Friday Oct 21, 2022 at 09:33 GMT_
_Originally opened as https://github.com/tinkoff-ai/etna/issues/994_

----

### 🚀 Feature Request

It seems we have not appropriate readme structure, it should be slightly improved

### Proposal

TODO

**Comment by d-a-bunin** [comment]
This issue is empty.
