### ISSUE TITLE
Add `HolidayTransform` the ability to work with other frequencies

### ISSUE THREAD

**Issue by ostreech1997** [etna-team/etna#239]
### 🚀 Feature Request

`HolidayTransform` can only work with a daily frequency or less. We can extend its functionality to other frequencies: weekly, monthly, quarterly, yearly.

### Proposal

- We add new `mode="days_count"`.
- This mode works only with weekly, monthly, quarterly and yearly frequencies (freqs like '3M', '4W' are also possible).
- We count the proportion of days with public holidays for each point. The procedure is as follows:

### Test cases

- Add test to check new mode:
  - different end freqs (e.g. "M")
  - different start freqs (e.g. "MS")
  - other frequency options (e.g. "5M")
- Add test to check that other frequencies in this mode are falling with an specific error
- Extend existing tests for `HolidayTransform` in `test_transforms/test_inference` to check new mode

**Comment by yellowssnake** [comment]
Надо ли кидать ошибку, если период в котором мы считаем частоту появления праздничных дней больше чем  период доступный нам в датасете(например на вход в days_count подаётся 2M, а данные есть только за месяц)
