### ISSUE TITLE
Implement TS2VecModel

### ISSUE THREAD

**Issue by egoriyaa** [etna-team/etna#245]
### 🚀 Feature Request

Starting the track of time series embeddings, implement one of appropriate models - `TS2VecModel`

### Proposal

Implement:
- Abstract class`BaseEmbeddingModel` with methods `fit`, `encode_segment`, `encode_window`, `load` and `save`
- Class `TS2VecModel(BaseEmbeddingModel)` overriding abstract methods of `BaseEmbeddingModel`

### Test cases

What should be checked:

- Fitting model
- Encoding with `encode_segment`
- Encoding with `encode_window`
- Saving pretrained model
- Loading pretrained model
  - Exception if there is no saved model
- Getting the same result when transforming dataset before saving and after loading model

**Comment by d-a-bunin** [comment]
Closed by #253.
