### ISSUE TITLE
[BUG] `DeseasonalityTransform` handles `period` incorrectly

### ISSUE THREAD

**Issue by alex-hse-repository** [etna-team/etna#278]
### 🐛 Bug Report

`DeseasonalityTransform` handles `period` incorrectly, know it ignores the value of `period` during [seasonal_decompose](https://github.com/etna-team/etna/blob/9903da15d7db9aa4622bdd91138857cc95f1d73c/etna/transforms/decomposition/deseasonal.py#L96). Value of period is infered from df.index.freq [here](https://www.statsmodels.org/dev/_modules/statsmodels/tsa/seasonal.html#seasonal_decompose:~:text=pfreq%20%3D%20freq_to_period(pfreq)) -- for daily data period is always 7

### Expected behavior

Pass `period` to `seasonal_decompose`

### Code
```
import pandas as pd
from etna.datasets import TSDataset
from etna.transforms import DeseasonalityTransform

df = pd.read_csv("data.csv") # Ask Chikov Aleksandr for data sample, you can use any data with annual peaks
df = df.rename(columns={"key":"segment", "value":"target"})
df_target = TSDataset.to_dataset(df)
ts = TSDataset(df=df_target, freq="D")

ts.plot()

transform = DeseasonalityTransform(in_column="target", period=365)
transform.fit(ts)
transform.transform(ts)

ts.plot()
```

Data with annual peaks
```
df = generate_ar_df(n_segments=1, periods=1400, start_time="2000-01-01")
df["target"] = np.sin(2 * np.pi * np.arange(1400)/7) + 10
df["is_holiday"] = False
df.loc[df["timestamp"].isin([
    "2000-05-09", "2001-05-09", "2002-05-09", "2003-05-09",
    "2000-03-08", "2001-03-08", "2002-03-08", "2003-03-08"
]), "target"] += 5
```

### Screenshots
Befor transform:
<img width="891" alt="Снимок экрана 2024-03-22 в 15 36 59" src="https://github.com/etna-team/etna/assets/55380696/d5df660c-74d2-4fde-841c-e6d12febb556">

After transform(expected that all annual peaks disappear)
<img width="890" alt="Снимок экрана 2024-03-22 в 15 37 17" src="https://github.com/etna-team/etna/assets/55380696/6c47a1a1-c8c7-40f0-8436-3c3ffa6d2baf">

### Checklist

- [X] Bug appears at the latest library version

**Comment by d-a-bunin** [comment]
It was fixed in ["Handling unaligned" data track](https://github.com/etna-team/etna/milestone/5).
