### ISSUE TITLE
Add "unofficial" holidays to `HolidaysTrransform`

### ISSUE THREAD

**Issue by alex-hse-repository** [etna-team/etna#280]
### 🚀 Feature Request

Since [v0.44](https://github.com/vacanza/python-holidays/releases/tag/v0.44) `holidays` package supports "unofficial" holidays for US, however we can't use them know in `HolidaysTransform`. It also might be useful to add unofficial holidays for RUS manually.   

### Proposal

1. Add support for "unofficial" holidays for US via adding corresponding parameter(see holidays docs)
2. Add support for "unofficial" holidays for RUS via adding corresponding parameter and manual list of unofficial holidays

### Test cases

Test that we generate unofficial holidays for US and RUS iso

### Additional context

The `categories` parameter appeared in `holidays` library only in version 0.28.0, but `etna` currently supports >= 0.13.

**Comment by d-a-bunin** [comment]
Moved the info into discussion (#333).
