### ISSUE TITLE
Add tutorial how to work with embedding models

### ISSUE THREAD

**Issue by egoriyaa** [etna-team/etna#297]
### 🚀 Feature Request

Add new tutorial notebook "210-embedding_models" how to work with embeddings models and embedding transforms.

### Proposal

To show in notebook:
* Direct usage of `TS2VecEmbeddingModel` and `TSTCCEmbeddingModel` without transform
  * `fit`, `encode_window` and `encode_segment` methods
  * `freeze` method
  * `save` and `load` methods
* Impact of embedding features
  * Fit any model on chosen dataset without additional features
  * Fit the same model on the same dataset with some features (like lags, fourier, etc)
  * Use `EmbeddingSegmentTransform` and `EmbeddingWindowTransform` to generate features with both embedding models
  * Fit the same model on the same dataset with embedding features. Try to get better results.

**Comment by d-a-bunin** [comment]
Closed by #304.
