### ISSUE TITLE
Problem with using regressors lags with AutoRegressivePipeline()

### ISSUE THREAD

**Issue by AndreiAvdko** [etna-team/etna#305]
### Checklist

- [X] I have searched the issues.
- [X] I have searched the docs.

### ❓ What is the issue?

Hi! I have problem with forecast in this code with using lags for regressor variables. Does this look like a problem or tell me what I'm doing wrong?

```
df = generate_ar_df(periods=100, start_time="2021-01-01", ar_coef=[1/2], n_segments=1)
# Add additional column with exogen var
random_values = np.random.rand(len(df))
df['regressor'] = random_values

ts = TSDataset(TSDataset.to_dataset(df), freq="D")

transform = LagTransform(in_column="target", lags=list(range(1, 20+1)))
transform_regres = LagTransform(in_column="regressor", lags=list(range(1, 20+1)))
ts.fit_transform(transforms=[transforms, transform_regres])

future_ts = ts.make_future(future_steps=3, transforms=[transform, transform_regres])

model = LinearPerSegmentModel()
pipeline = AutoRegressivePipeline(model = model, horizon = 3, step=1)
pipeline.fit(ts=ts)
forecast_ts = model.forecast(ts)
```

Before this line `pipeline.fit(ts=ts)` code run succesful, but when I try get forecast I get next error:

> ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

And if I use only lags for target, all working ok

**Comment by egoriyaa** [comment]
Hi!
You should use `lags` >= `horizon`. Now you are using `lags` starting from 1 and `horizon`=3
Also you need to pass `future_ts` to `model.forecast()`

Why don't you use `Pipeline` with transforms and its `forecast` method? It seems clearer and easier for me.
See [tutorial](https://github.com/etna-team/etna/blob/master/examples/101-get_started.ipynb) for more details

**Comment by egoriyaa** [comment]
Hi!
Your code can be rewritten like:

```
df = generate_ar_df(periods=100, start_time="2021-01-01", ar_coef=[1/2], n_segments=1)

random_values = np.random.rand(len(df))
df_exog = df.copy()
df_exog["target"] = random_values
df_exog.rename(columns={"target": "exog"}, inplace=True)

ts = TSDataset(df, df_exog=df_exog, freq="D")

transform = LagTransform(in_column="target", lags=list(range(1, 20+1)))
transform_regres = LagTransform(in_column="exog", lags=list(range(3, 20+1)))

model = LinearPerSegmentModel()
pipeline = AutoRegressivePipeline(model = model, transforms=[transform, transform_regres], horizon = 3, step=1)
pipeline.fit(ts=ts)
forecast_ts = pipeline.forecast()
```

Make the following changes:

1. Store your exog data in `df_exog`.
2. Exog data is not being forecasted in a pipeline, so it should be known in the future. To achieve that you should increase the minimum lag value for this feature up to horizon.
3. Don't mix up interfaces. If you are going to use `AutoRegressivePipeline`, don't use `make_future` or transforms directly, pipeline does this logic automatically. Check our 101 tutorial.

**Comment by AndreiAvdko** [comment]
Thank you very much for your help, this solved my problem! Do you know if there are any plans to add recursive forecasting to the autoregressive pipeline also for exogenous variables? To be able to use first lags with regressors:
`transform_regres = LagTransform(in_column="exog", lags=list(range(1, __some values_)))`
Seems like it could be useful for some tasks
