### ISSUE TITLE
 Public datasets in `etna.datasets`

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#4]
<a href="https://github.com/martins0n"><img src="https://avatars.githubusercontent.com/u/33594071?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [martins0n](https://github.com/martins0n)**
_Friday Jan 28, 2022 at 12:24 GMT_
_Originally opened as https://github.com/tinkoff-ai/etna/issues/467_

----

### 🚀 Feature Request

We have synthetic datasets now.
It's helpfull for model sanity checks and testing.
But real data is more complex.

### Motivation

- Performance testing of frequently used datasets in papers. 
- Examples enhancement
- Benchmarking in unified framework

### Proposal

- Add `load_dataset(dataset_name: str, ..., *args, **kwargs) -> Dataset` 
- `Dataset`
```python
class Dataset:
    train: Lazy[TSDataset]
    test: Lazy[TSDataset]
    dataset_path: Optional[pathlib.Path]
    metadata: dict
```
- M4 ( every seasonalities are independent ), M5, Household Electric Power Consumption, M3, Web Traffic Time Series Forecasting -- datasets to add. 
- Format for saving on disk -- jsonl. Every line is `{"target": array<float>, "segment": str, "horizon": int, "freq": int ...}`
- Data is loaded from direct link

### Additional context

- Before publishing-copy data, we should clarify possible licence issues.

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by ostreech1997** [comment]
Closed by https://github.com/etna-team/etna/milestone/3
