### ISSUE TITLE
[DOCS] Add `**kwargs` param description for models

### ISSUE THREAD

**Issue by ArtemLiA** [etna-team/etna#445]
### 📖 Documentation improvement

Hi! Looking through the documentation of some models, I noticed that some of them don't have a description of `**kwargs` parameters. I think we should fix it.

A list of models that don't have `**kwargs` argument description:
- [x] `CatBoostMultiSegmentModel` ([docs link](https://docs.etna.ai/stable/api_reference/api/etna.models.CatBoostMultiSegmentModel.html))
- [x] `CatBoostPerSegmentModel` ([docs link](https://docs.etna.ai/stable/api_reference/api/etna.models.CatBoostPerSegmentModel.html))
- [x] `ElasticMultiSegmentModel` ([docs link](https://docs.etna.ai/stable/api_reference/api/etna.models.ElasticMultiSegmentModel.html))
- [x] `ElasticPerSegmentModel` ([docs link](https://docs.etna.ai/stable/api_reference/api/etna.models.ElasticPerSegmentModel.html))
- [x] `LinearMultiSegmentModel` ([docs link](https://docs.etna.ai/stable/api_reference/api/etna.models.LinearMultiSegmentModel.html))
- [x] `LinearPerSegmentModel` ([docs link](https://docs.etna.ai/stable/api_reference/api/etna.models.LinearPerSegmentModel.html))

**Comment by d-a-bunin** [comment]
Usually, these kwargs mean that these additional parameters are added into the model constructor. It looks like a good idea to point this out in documentation.

And may be we should give a link to the place there user could see all the parameters. I don't think we should list all the possible parameters, because they could change in the future.

**Comment by ArtemLiA** [comment]
Yes, I meant that we should add a mention that these parameters are added into model constructor and add link to the models. So, I am going to do it.
