### ISSUE TITLE
Add function `etna.datasets.load_dataset` to public API

### ISSUE THREAD

**Issue by ArtemLiA** [etna-team/etna#465]
### 🚀 Task description

We need to add function `etna.datasets.load_dataset` to public API, so users can see `load_dataset` docs in the API References. 

### Plan

Firstly, we should add cross-references pages:
- Make in a "User guide" page link to load_dataset, it will allow users to check the parameters
- Make in `load_dataset` reference to "User guide" page for users to see the list of all available datasets.

Secondly, we need to add link to `load_dataset` function in the datasets.rst.

### Additional context

This task was previously discussed in #447

**Comment by d-a-bunin** [comment]
@ostreech1997 , what do you think?
