### ISSUE TITLE
[BUG] Remove leading zeros from segment names when using `forecast` command

### ISSUE THREAD

**Issue by fuglaeff** [etna-team/etna#468]
### 🐛 Bug Report

When the `forecast` command reads data from a CSV, it uses the default behavior of the Pandas library, which converts a numeric name to an integer.

Related issue https://github.com/pandas-dev/pandas/issues/31821

### Expected behavior

Storing numeric names as a string

### How To Reproduce

```python3
from pathlib import Path

from etna.commands import forecast

'''
dataset.csv
    =============  ===========  ==========
      timestamp      segment      target
    =============  ===========  ==========
    2020-01-01     000123456         1
    2020-01-02     000123456         2
    2020-01-03     000123456         3
    2020-01-04     000123456         4
    ...
    2020-01-10     000654321        10
    2020-01-11     000654321        20
    =============  ===========  ==========
'''


def main() -> None:
    forecast(
        config_path=Path("config.yaml"),
        forecast_config_path=Path("config.yaml"),
        target_path=Path("dataset.csv"),
        freq="D",
        output_path=Path("result.csv"),
    )


if __name__ == "__main__":
    main()

'''
result.csv
    =============  ===========  ==========
      timestamp      segment      target
    =============  ===========  ==========
    2020-01-01     123456         1
    2020-01-02     123456         2
    2020-01-03     123456         3
    2020-01-04     123456         4
    ...
    2020-01-10     654321        10
    2020-01-11     654321        20
    =============  ===========  ==========
'''
```

### Checklist

- [X] Bug appears at the latest library version

**Comment by d-a-bunin** [comment]
In the code of the library we assume that `segment` has type `str`, so it is indeed strange to convert it to `int` during reading and then convert back to `str` during creation of `TSDataset`.

Do you think we should somehow specify the type of the column during reading? Do you know how to do i?

**Comment by fuglaeff** [comment]
To avoid this behavior, I think you can use the `dtypes={"segments": "string"}` param for `pandas.read_csv`

**Comment by d-a-bunin** [comment]
I think it is a reasonable solution and could be tried at least.
