### ISSUE TITLE
[BUG] Clustering fails of `scikit-learn>=1.4`

### ISSUE THREAD

**Issue by alex-hse-repository** [etna-team/etna#516]
### 🐛 Bug Report

Since version 1.4 parameter `affinity` was renamed to `metric` in `AgglomerativeClustering`, so clustering fails with
```
TypeError: __init__() got an unexpected keyword argument 'affinity'
```

We have wrong constraints on [scikit-learn version](https://github.com/etna-team/etna/blob/a1647bbb1299056208f243c826f7b483e85f61ad/pyproject.toml#L45) in `pyproject.toml`

### Expected behavior

Clustering works fine after installing the library

### How To Reproduce

Install library in environment with scikit-learn >= 1.4.0 and run example notebook with clustering

### Checklist

- [X] Bug appears at the latest library version

**Comment by d-a-bunin** [comment]
Closed by #529.
