### ISSUE TITLE
Add multiversion switcher into documentation

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#54]
### 🚀 Feature Request

Currently, we have two versions of documentation: latest and stable. We should add switch to choose between them.

### Proposal

Add [switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#add-a-json-file-to-define-your-switcher-s-versions) into latest version.

[Set up the theme to point to the latest switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#add-a-json-file-to-define-your-switcher-s-versions).

Configure [checking matching version](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#add-a-json-file-to-define-your-switcher-s-versions).

### Additional context

Is blocked by #52.

**Comment by d-a-bunin** [comment]
Closed by #55.
