### ISSUE TITLE
get_started: add description of all etna modules

### ISSUE THREAD

**Issue by Mr-Geekman** [etna-team/etna#7]
<a href="https://github.com/iKintosh"><img src="https://avatars.githubusercontent.com/u/25372584?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iKintosh](https://github.com/iKintosh)**
_Wednesday Feb 02, 2022 at 17:21 GMT_
_Originally opened as https://github.com/tinkoff-ai/etna/issues/495_

----

### 🚀 Feature Request

This way we can describe the concept of how etna package is organised.

### Motivation

It may be not clear for the users where to look for etna modules.

### Proposal

Look at the https://github.com/shazow/unstdlib.py#organization--philosophy and adapt it to etna library.
Only we write it in get_started notebook.

### Alternatives

Create documentation page.

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by d-a-bunin** [comment]
I think it isn't relevant with a [new documentation](https://docs.etna.ai/stable/api_reference.html).
