### ISSUE TITLE
[BUG] Method `to_dict` doesn't work for `SklearnPerSegmentModel` and `SklearnMultiSegmentModel`

### ISSUE THREAD

**Issue by d-a-bunin** [etna-team/etna#76]
### 🐛 Bug Report

Method `to_dict` doesn't work for `SklearnPerSegmentModel` and `SklearnMultiSegmentModel`.

### Expected behavior

It should work.

### How To Reproduce

```python
from etna.models import SklearnPerSegmentModel
from sklearn.linear_model import LinearRegression 

model = SklearnPerSegmentModel(regressor=LinearRegression())
model.to_dict()
```

It fails with error:
```
KeyError: 'regressor'
```

Probably, the solution is to set `self.regressor` in these models.

### Checklist

- [X] Bug appears at the latest library version

**Comment by GoshaLetov** [comment]
Hey I'm new to this but feel I can do this, do you mind if you assign this one to me?

**Comment by d-a-bunin** [comment]
Hi! Let's try!
Are you familiar with a process of creating a pull request for a repository? As I remember, you should 
1. Make a fork, 
2. Make a separate branch for the task 
3. Push the changes to your fork
4. Create a pull request into this repository

After that, we'll start an iterative process of reviews and fixes. After merging we'll list you in our [list of contributors](https://github.com/etna-team/etna#etnacontributors) (if we'll forget about it remind us).
